from config.settings import PROJECT_VERSION, PROJECT_TITLE, PROJECT_DESCRIPTION

SPECTACULAR_SETTINGS = {
    'TITLE': PROJECT_TITLE,
    'DESCRIPTION': PROJECT_DESCRIPTION,
    'VERSION': PROJECT_VERSION,
    'SERVE_INCLUDE_SCHEMA': False,
}