from config.settings import PROJECT_DESCRIPTION, PROJECT_TITLE, PROJECT_VERSION

SPECTACULAR_SETTINGS = {
    'TITLE': PROJECT_TITLE,
    'DESCRIPTION': PROJECT_DESCRIPTION,
    'VERSION': PROJECT_VERSION,
    'SERVE_INCLUDE_SCHEMA': False,
}
