repos:
- hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-yaml
  - exclude: launch.json
    id: check-json
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
- hooks:
  - args:
    - --profile
    - black
    - --filter-files
    exclude: __init__.py
    id: isort
  repo: https://github.com/pycqa/isort
  rev: 5.13.2
- hooks:
  - args:
    - --py313-plus
    id: pyupgrade
  repo: https://github.com/asottile/pyupgrade
  rev: v3.19.0
- hooks:
  - args:
    - --max-line-length=120
    - --in-place
    id: autopep8
  repo: https://github.com/hhatto/autopep8
  rev: v2.3.1
- hooks:
  - additional_dependencies:
    - flake8-bugbear
    args:
    - --ignore=E501,F821
    - --max-line-length=120
    exclude: __init__.py
    id: flake8
  repo: https://github.com/PyCQA/flake8
  rev: 7.1.1
- hooks:
  - id: mypy
  repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.9.0
- hooks:
  - always_run: true
    entry: ./scripts/run_tests.sh
    id: django-test
    language: script
    name: run django tests
    types: []
  repo: local
- hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - pre-push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v4.1.0
