# Generated by Django 5.1.4 on 2024-12-22 08:44
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[tuple[str, str]] = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='порядок отображения')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('status', models.BooleanField(choices=[(True, 'Активно'),
                 (False, 'Не активно')], default=True, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'db_table': 'categories',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='порядок отображения')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='название')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='описание')),
                ('count', models.PositiveIntegerField(verbose_name='количество')),
                ('status', models.BooleanField(choices=[(True, 'Активно'),
                 (False, 'Не активно')], default=True, verbose_name='статус')),
                ('categories', models.ManyToManyField(to='catalog.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'products',
            },
        ),
    ]
