# Generated by Django 5.1.4 on 2024-12-27 15:25

from django.db import migrations, models

import apps.catalog.utils.image


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='порядок отображения')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название')),
                ('price', models.PositiveIntegerField(verbose_name='стоимость')),
                ('image', models.ImageField(upload_to=apps.catalog.utils.image.get_ingredient_image_path, verbose_name='изображение')),
                ('status', models.BooleanField(choices=[(True, 'Активно'),
                 (False, 'Не активно')], default=True, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'db_table': 'ingredients',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='catalog.category', verbose_name='категории'),
        ),
    ]
