# Generated by Django 5.1.4 on 2024-12-21 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('description', models.CharField(max_length=200, verbose_name='описание')),
                ('count', models.PositiveIntegerField(verbose_name='количество')),
                ('status', models.BooleanField(choices=[(True, 'Активно'),
                 (False, 'Не активно')], default=True, verbose_name='статус')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='catalog.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'products',
            },
        ),
    ]
