# Generated by Django 5.1.4 on 2024-12-28 13:22

import django.db.models.deletion
from django.db import migrations, models

import apps.catalog.utils.image


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_ingredient_alter_product_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(to='catalog.ingredient', verbose_name='ингредиенты'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(verbose_name='порядок отображения'),
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='порядок отображения')),
                ('status', models.BooleanField(choices=[(True, 'Активно'),
                 (False, 'Не активно')], default=True, verbose_name='статус')),
                ('price', models.PositiveIntegerField(verbose_name='стоимость')),
                ('image', models.ImageField(upload_to=apps.catalog.utils.image.get_variation_image_path, verbose_name='изображение')),
                ('pizza_size', models.IntegerField(blank=True, choices=[
                 (25, '25 см'), (30, '30 см'), (35, '35 см')], null=True, verbose_name='размер пиццы')),
                ('pizza_type', models.CharField(blank=True, choices=[
                 ('traditional', 'традиционное'), ('slim', 'тонкое')], null=True, verbose_name='тип теста')),
                ('count', models.IntegerField(blank=True, choices=[(1, '1 шт'), (2, '2 шт'), (3, '3 шт'), (4, '4 шт'), (
                    5, '5 шт'), (10, '10 шт'), (8, '8 шт'), (16, '16 шт')], null=True, verbose_name='кол-во, шт.')),
                ('portion_size', models.CharField(blank=True, choices=[
                 ('small', 'маленькая'), ('average', 'средняя'), ('big', 'большая')], null=True, verbose_name='размер порции')),
                ('volume', models.CharField(blank=True, choices=[
                 ('0.3', '0.3 л'), ('0.4', '0.4 л'), ('0.45', '0.45 л'), ('0.5', '0.5 л'), ('1', '1 л')], null=True, verbose_name='объем, л')),
                ('weight', models.CharField(blank=True, choices=[
                 ('0.5', '0.5 кг')], null=True, verbose_name='масса, кг')),
                ('mass', models.IntegerField(blank=True, null=True, verbose_name='масса, г')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'Вариация',
                'verbose_name_plural': 'Вариации',
                'db_table': 'variations',
            },
        ),
        migrations.CreateModel(
            name='VariationToIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='стоимость')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.ingredient')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.variation')),
            ],
            options={
                'verbose_name': 'Вариация-ингредиент',
                'verbose_name_plural': 'Вариации-ингредиенты',
                'db_table': 'variation_to_ingredient',
            },
        ),
        migrations.AddField(
            model_name='variation',
            name='ingredients',
            field=models.ManyToManyField(through='catalog.VariationToIngredient',
                                         to='catalog.ingredient', verbose_name='доп.ингредиенты'),
        ),
    ]
