# Generated by Django 5.1.4 on 2024-12-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_ingredient_price_product_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='price',
            field=models.PositiveIntegerField(verbose_name='стоимость, руб'),
        ),
        migrations.AlterUniqueTogether(
            name='variationtoingredient',
            unique_together={('variation', 'ingredient')},
        ),
    ]
