# Generated by Django 5.1.4 on 2025-01-02 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_variation_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parent_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='product', to='catalog.category', verbose_name='основная категория'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='catalog.category', verbose_name='категории'),
        ),
    ]
