# Generated by Django 5.1.4 on 2025-01-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_parent_category_alter_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='variationtoingredient',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='порядок отображения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='catalog.ingredient', verbose_name='ингредиенты'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='count',
            field=models.IntegerField(blank=True, choices=[(1, '1 шт'), (2, '2 шт'), (3, '3 шт'), (4, '4 шт'), (
                5, '5 шт'), (8, '8 шт'), (10, '10 шт'), (16, '16 шт')], null=True, verbose_name='кол-во, шт.'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='pizza_type',
            field=models.CharField(blank=True, choices=[(
                'traditional', 'Традиционное'), ('slim', 'Тонкое')], null=True, verbose_name='тип теста'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='portion_size',
            field=models.CharField(blank=True, choices=[(
                'small', 'Маленькая'), ('average', 'Средняя'), ('big', 'Большая')], null=True, verbose_name='размер порции'),
        ),
    ]
