# Generated by Django 5.1.4 on 2025-01-17 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_variationtoingredient_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='ingredients', to='catalog.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='variations', to='catalog.product', verbose_name='товар'),
        ),
    ]
